name: AWESOME SAMPLE MATRIX

on:
  push:
    branches:
      - main
jobs:
  artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo:
          - ghcr.io
        bar:
          - value_1
          - value_2
        include:
          - bar: value_1
            buzz: buzz_1 # additional matrix
            foo: gcr.io # Additional element to array
          - bar: value_2
            buzz: buzz_2 # additional matrix
    steps:
      - name: Show matrix
        run: |
          echo "${{ matrix.foo }}"
          echo "${{ matrix.bar }}"
          echo "${{ matrix.buzz }}"

